name: Trigger auto deployment for containerapp ansalemo-dockerhub-ca-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ansalemo-dockerhub-ca-test-AutoDeployTrigger-cd87162a-5d86-402c-8b02-de9a7c7c5806.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://ajssalemo.docker.io
          username: ${{ secrets.ANSALEMODOCKERHUBCATEST_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMODOCKERHUBCATEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://ajssalemo.docker.io/ansalemo-dockerhub-ca-test:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMODOCKERHUBCATEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n ansalemo-dockerhub-ca-test -g ansalemo-ca-test-rg --server https://ajssalemo.docker.io --username  ${{ secrets.ANSALEMODOCKERHUBCATEST_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMODOCKERHUBCATEST_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-dockerhub-ca-test -g ansalemo-ca-test-rg --image https://ajssalemo.docker.io/ansalemo-dockerhub-ca-test:${{ github.sha }}
